USE PlumbingAgency;
GO

INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Glens Plumbing', 'http://glensplumbing.com/', '(214) 429-4634', 'NULL', 'Dallas, TX', 'Dallas', 'TX', 'Drain Cleaning, Sewer Repair, 4.9 Stars', 75, 'PRIORITY', 0, 0, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('1-800-Plumber Dallas', 'https://1800plumber.com/dallas-tx/', '(214) 935-8547', 'NULL', 'Dallas, TX', 'Dallas', 'TX', '24/7 Emergency Plumbing', 55, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('448 Plumbing', 'https://www.448plumbing.com/', 'NULL', 'NULL', 'Dallas, TX', 'Dallas', 'TX', 'Emergency Plumbing, Licensed', 45, 'PRIORITY', 1, 0, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Texas Rooter', 'https://www.texasrooter.com/', 'NULL', 'NULL', 'Dallas, TX', 'Dallas', 'TX', 'Plumbing, Drain Cleaning, 24-Hour', 45, 'PRIORITY', 1, 0, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Baker Brothers Plumbing', 'https://bakerbrothersplumbing.com/', '(214) 296-2136', 'NULL', 'Dallas, TX', 'Dallas', 'TX', 'Emergency Plumbing, 24 Hour', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Emergency Plumbing on Call', 'https://emergencyplumbingoncall.com/', '(972) 597-5959', 'NULL', 'Dallas, TX', 'Dallas', 'TX', '24/7 Emergency, 20+ Years Experience', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Lee''s Air Plumbing', 'https://leesair.com/', 'NULL', 'NULL', 'Dallas, TX', 'Dallas', 'TX', 'Emergency Plumbing, HVAC', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Pure Plumbing DFW', 'https://www.pureplumbingdfw.com/', 'NULL', 'NULL', 'Dallas, TX', 'Dallas', 'TX', '24/7 Emergency Plumbing', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Reliant Plumbing', 'https://reliantplumbing.com/', 'NULL', 'NULL', 'Dallas, TX', 'Dallas', 'TX', '24 Hour Emergency Plumbing', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Astar Air Conditioning', 'https://astardfw.com/', 'NULL', 'NULL', 'Dallas-Fort Worth, TX', 'Dallas', 'TX', 'Emergency Plumbing, Fast Response', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('247 Las Vegas Plumber', 'https://247lasvegasplumber.com/', 'NULL', 'NULL', 'Las Vegas, NV', 'Las Vegas', 'NV', '24/7, 60 Minutes or FREE', 75, 'PRIORITY', 0, 0, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Larkin Plumbing', 'https://www.larkinplumbingservice.com/', 'NULL', 'NULL', 'Las Vegas, NV', 'Las Vegas', 'NV', 'Since 1936, 24 Hour Emergency', 55, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Precision Plumbing LV', 'https://www.precisionplumbinglv.com/', 'NULL', 'NULL', 'Las Vegas, NV', 'Las Vegas', 'NV', '24/7 Plumbing, Las Vegas Valley', 55, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Roto-Rooter Las Vegas', 'https://www.rotorooter.com/lasvegas/', '(702) 931-3831', 'NULL', 'Las Vegas, NV', 'Las Vegas', 'NV', '24/7 Emergency, Fast Response', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Anytime Plumbing Vegas', 'https://anytimeplumbingvegas.com/', '(725) 237-1727', 'NULL', 'Las Vegas, NV', 'Las Vegas', 'NV', '24-Hour Emergency, Special Offers', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Monkey Wrench Plumbing', 'https://www.monkeywrenchlv.com/', '(702) 900-5992', 'NULL', 'Las Vegas, NV', 'Las Vegas', 'NV', 'Emergency Plumbing, Free Quote', 30, 'PRIORITY', 0, 1, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Code Red Emergency Plumbing', 'https://coderedplumbing.com/', '(702) 949-6599', 'NULL', 'Las Vegas, NV', 'Las Vegas', 'NV', 'Emergency, Las Vegas Favorite', 30, 'PRIORITY', 0, 1, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('24 HR Water Cleanup', 'https://24hrwatercleanup.com/', '(702) 978-0133', 'NULL', 'Las Vegas, NV', 'Las Vegas', 'NV', '24 HR Emergency, Water Emergency', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Rodeo Plumbing and Drain', 'https://rodeo-plumbing.com/', 'NULL', 'NULL', 'Las Vegas, NV', 'Las Vegas', 'NV', 'Emergency Plumbing', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Orchard Plumbing', 'https://orchardplumbing.vegas/', 'NULL', 'NULL', 'Las Vegas, NV', 'Las Vegas', 'NV', '24-Hour Emergency, Licensed', 20, 'PRIORITY', 1, 1, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Phoenix Plumbing', 'https://phoenixplumbing.co/', '(602) 834-1208', 'NULL', 'Phoenix, AZ', 'Phoenix', 'AZ', 'Emergency Plumbing, 60-Min Response', 75, 'PRIORITY', 0, 0, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('The Aussie Plumber', 'https://theaussieplumber.com/', 'NULL', 'NULL', 'Phoenix, AZ', 'Phoenix', 'AZ', 'Plumbing, Repairs, Replacements', 75, 'PRIORITY', 0, 0, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Rock Plumbing AZ', 'https://rockplumbingaz.com/', 'NULL', 'NULL', 'Phoenix, AZ', 'Phoenix', 'AZ', 'Emergency Plumbing, 24/7', 75, 'PRIORITY', 0, 0, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Dr. Pipes Phoenix', 'https://www.drpipes.com/az/maricopa/phoenix.html', 'NULL', 'NULL', 'Phoenix, AZ', 'Phoenix', 'AZ', '24/7 Emergency Plumbing', 55, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Okane Plumbing', 'https://phoenix-az.okaneplumbingandelectrics.com/', '(833) 876-1141', 'NULL', 'Phoenix, AZ 85044', 'Phoenix', 'AZ', '24 Hour Emergency Plumbing', 45, 'PRIORITY', 1, 0, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Roto-Rooter Phoenix', 'https://www.rotorooter.com/phoenix/', '(623) 915-0995', 'NULL', 'Phoenix, AZ', 'Phoenix', 'AZ', '24 Hour Emergency Plumbing, Drain Cleaning', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Parker & Sons', 'https://www.parkerandsons.com/', 'NULL', 'NULL', 'Phoenix, AZ', 'Phoenix', 'AZ', 'Emergency Plumber, HVAC, Electrical', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Simon''s Plumbing', 'https://simonsplumbingaz.com/', '(602) 739-4117', 'simon@simonsplumbingaz.com', 'Phoenix, AZ', 'Phoenix', 'AZ', 'Full-Service Plumbing, 24/7', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Quail Plumbing', 'https://www.quailplumbing.com/', '(602) 493-9822', 'NULL', 'Phoenix, AZ 85024', 'Phoenix', 'AZ', 'Drain Cleaning, 24 Hr Emergency', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Howard Air & Plumbing', 'https://howardair.com/', '(480) 508-9866', 'NULL', 'Phoenix, AZ', 'Phoenix', 'AZ', 'Plumbing Repair, 24 Hour Emergency', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('All Hours Plumber Tampa', 'https://allhoursplumber.com/', 'NULL', 'NULL', 'Tampa, FL', 'Tampa', 'FL', '24/7 Emergency, Tampa Bay Area', 75, 'PRIORITY', 0, 0, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('ABC Plumbing Tampa Bay', 'https://www.4abc.com/', '(813) 452-5952', 'NULL', 'Tampa Bay, FL', 'Tampa', 'FL', 'Emergency Plumbing Services', 75, 'PRIORITY', 0, 0, 0, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Tampa Emergency Plumbing', 'https://emergencyplumbertampa.com/', '(813) 489-6968', 'NULL', 'Tampa, FL', 'Tampa', 'FL', '24 Hour Plumbers, Reliable', 55, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Everyday Plumber', 'https://everydayplumber.com/', 'NULL', 'NULL', 'Tampa, FL', 'Tampa', 'FL', 'Emergency, Residential, Commercial', 55, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Dr. Pipes Tampa', 'https://www.drpipes.com/fl/hillsborough/tampa.html', 'NULL', 'NULL', 'Tampa, FL', 'Tampa', 'FL', '24/7 Emergency Plumbers', 55, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Roto-Rooter Tampa', 'https://www.rotorooter.com/tampa/', '(813) 980-6000', 'NULL', 'Tampa, FL', 'Tampa', 'FL', '24/7 Emergency Plumbing', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Benjamin Franklin Plumbing Tampa', 'https://www.benjaminfranklinplumbing.com/tampa/', 'NULL', 'NULL', 'Tampa, FL', 'Tampa', 'FL', 'Emergency Plumbing, Voted Best (Forbes)', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('1 Tom Plumber Tampa', 'https://www.1tomplumber.com/tampa-fl/', 'NULL', 'NULL', 'Tampa, FL', 'Tampa', 'FL', '24 Hour Emergency, Every Day/Night', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Grable Plumbing & Air', 'https://grableplumbing.com/', '(813) 239-3636', 'NULL', 'Tampa, FL', 'Tampa', 'FL', 'Emergency 24hr, Free Estimate', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Stewart Bros Plumbing', 'https://stewartbrosplumbing.com/', '(813) 602-0700', 'NULL', 'Tampa, FL', 'Tampa', 'FL', '24/7 Plumbing', 0, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Wood''s Plumbing', 'https://woodsplumbing.com/', '(520) 682-2233', 'NULL', 'Tucson, AZ', 'Tucson', 'AZ', 'Emergency Plumbing, Drain, Water Services', 55, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Big Ed''s Plumbing', 'https://bigedsplumbing.com/', 'NULL', 'NULL', 'Tucson, AZ 85730', 'Tucson', 'AZ', 'Emergency Plumbing, 24/7 Service', 55, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Tucson 24 Hour Plumber and Drain', 'http://tucson24hourplumberanddrain.com/', '(520) 252-4044', 'NULL', '7729 E. Clarence Pl - Tucson AZ 85715', 'Tucson', 'AZ', 'Emergency, Water Heater, Drain Cleaning', 55, 'PRIORITY', 0, 0, 1, 1, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('A.S.G. Plumbing Enterprises', 'https://tucsonazplumber.com/', '(520) 333-2121', 'NULL', 'Tucson, AZ 85730', 'Tucson', 'AZ', 'Emergency Plumbing, Drain Cleaning, Water Heater', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Cummings Plumbing Heating and Cooling', 'https://cummingsplumbingtucsonaz.com/', '(520) 333-2121', 'NULL', 'Tucson, AZ', 'Tucson', 'AZ', 'Plumbing, Heating, Cooling, Emergency', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Roto-Rooter Tucson', 'https://www.rotorooter.com/tucson/', '(520) 518-3769', 'NULL', 'Tucson, AZ', 'Tucson', 'AZ', 'Emergency Plumbing, Drain Services', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Al Coronado Plumbing', 'https://alcoronadoplumbing.com/', 'NULL', 'NULL', 'Tucson, AZ', 'Tucson', 'AZ', 'Residential Plumbing, Commercial', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Right Now Plumbing', 'https://rightnowplumbingtucson.com/', 'NULL', 'NULL', 'Tucson, AZ', 'Tucson', 'AZ', 'Emergency Plumbing, Licensed, Insured', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('Tucson Plumbing Pros', 'https://tucsonplumbingprosaz.com/', '(520) 438-6111', 'NULL', 'Tucson, AZ', 'Tucson', 'AZ', '24 Hour Plumbing, Same Day Service', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());
INSERT INTO Leads (BusinessName, Website, Phone, Email, Address, City, State, Services, LeadScore, Status, HasClickToCall, HasStickyCTA, HasWeakHeadline, HasPoorMobile, CreatedAt, UpdatedAt, AuditedAt)
VALUES ('On The Way Plumbing', 'https://otwplumbing.com/', 'NULL', 'NULL', 'Tucson, AZ', 'Tucson', 'AZ', 'Plumbing Services', 30, 'PRIORITY', 1, 1, 0, 0, GETDATE(), GETDATE(), GETDATE());